<?php
	$now=date("s");
	if($now=='00'){
		echo'ジャストタイム!!';
	}
	elseif($now=='11'||$now=='22'||$now=='33'||$now=='44'||$now=='55'){
		echo'ゾロ目!';
	}
	else{
		echo'外れ';
	}
	echo'<br>アクセスした瞬間の秒は'.$now.'でした';
?>